services:
  db:
    image: mysql:8.4
    restart: always
    container_name: bacterial_growth_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE:      'BacterialGrowth'
      MYSQL_USER:          'bacterial_growth'
      MYSQL_PASSWORD:      'nVI8imBD3bl24pcP'
      MYSQL_ROOT_PASSWORD: 'nVI8imBD3bl24pcP'
