services:
  mgrowthdb_mysql:
    image: mysql:8.4
    restart: always
    container_name: mgrowthdb_mysql
    ports:
      # Currently, on our production, port 3306 is taken
      - "3307:3306"
    environment:
      # The credentials are hardcoded, because this database is not expected to
      # be exposed to the outer world:
      MYSQL_DATABASE:      'BacterialGrowth'
      MYSQL_USER:          'bacterial_growth'
      MYSQL_PASSWORD:      'nVI8imBD3bl24pcP'
      MYSQL_ROOT_PASSWORD: 'nVI8imBD3bl24pcP'
    volumes:
      - ./var/mysql/:/var/lib/mysql/:rw
  mgrowthdb_redis:
    image: redis:7.4-alpine
    restart: always
    container_name: mgrowthdb_redis
    ports:
      - 6379
