services:
  mgrowthdb_app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/prod-server
    ports:
      - "8081:8081"
    volumes:
      - ./var:/home/var:rw
    depends_on:
      mgrowthdb_mysql:
        condition: 'service_healthy'
      mgrowthdb_redis:
        condition: 'service_started'
    environment:
      APP_ENV:    'production'
      REDIS_HOST: 'mgrowthdb_redis'
      REDIS_PORT: '6379'
      DOCKER:     '1'

  mgrowthdb_mysql:
    image: mysql:8.4
    restart: always
    container_name: mgrowthdb_mysql
    ports:
      - 3306
    environment:
      MYSQL_DATABASE:      'BacterialGrowth'
      MYSQL_USER:          'bacterial_growth'
      MYSQL_PASSWORD:      'nVI8imBD3bl24pcP'
      MYSQL_ROOT_PASSWORD: 'nVI8imBD3bl24pcP'
    volumes:
      - ./var/mysql/:/var/lib/mysql/:rw
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1s
      timeout: 20s
      retries: 10

  mgrowthdb_redis:
    image: redis:7.4-alpine
    restart: always
    container_name: mgrowthdb_redis
    ports:
      - 6379
