[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pytest_env]
APP_ENV = "test"

[tool.coverage.run]
omit = [
  "legacy/*",
  "tests/*",
  "streamlit/*",
  ".micromamba/*",
]
[tool.coverage.html]
directory = "docs/test_coverage"
