[[pages]]
path = "app.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "pages/Database_Search.py"
name = "Search"
icon = ":mag:"

[[pages]]
path = "pages/Visualization_Dashboard.py"
name = "Dashboard"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/Upload_Data.py"
name = "Upload data"
icon = ":outbox_tray:"

[[pages]]
path = "pages/Help.py"
name = "Help"
icon = ":question:"

[[pages]]
path = "pages/About_Us.py"
name = "About us"
icon = ":lab_coat:"
